server:
  tomcat:
    accept-count: 5
#    Connection이 max, 즉 full일 때, 들어온 요청에 대해 OS에서 제공하는 Queue 길이.
#    (OS는 해당 설정을 무시하고 다른 큐를 사용할 수 있음)
#    큐 또한 다 찼다면, 이후 요청에 대해서는 거절(refuse) 또는 시간 초과(time out)을 발생시킴.
    max-connections: 4
#    서버가 승인하고 실행할 수 있는 최대 connection의 수.
#  Connection이 다 찼다면, 이후 요청들에 대해서는 승인(accept)은 하지만, 실행(process)은 하지 않음.
#  해당 요청들은 accept-count 설정에 따라 큐에 등록된다.
#  서버가 다시 승인+실행을 하기 위해서는 요청 수가 max-connections 밑으로 다시 떨어져야 함.
    threads:
      max: 3
#  Connector에 의해 요청을 처리하는 스레드가 몇 개 생성될 수 있는 지를 설정한다.
#  즉, 동시에 몇 개의 요청을 처리할 수 있는 지를 정의한다. (DEFAULT 200)
#  만약, executor 가 해당 connector와 관련되어 있다면, maxThreads 설정이 무시된다.
#  → Connector는 서버 내부의 스레드 풀을 사용하지 않고, executor를 사용하기 때문
